version: '2.4'

services:
  geolookup:
    image: advtr/geolookup:${TAG:-main}
    depends_on:
      - elasticsearch
    container_name: geolookup
    networks:
      - datastore
    ports:
      - 3000:3000
    environment:
      # Remnant of being included in geospatial
      - ES_INDEX=geospatial
      # Connect to the datastore
      - ES_HOST=http://elasticsearch:9200
      # Uncomment to add extra log levels for testing
      # - LOGLEVEL=verbose
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    networks:
      - datastore
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

networks:
  datastore:
